package br.com.zup.edu.chaves

import br.com.zup.edu.utils.error.InstituicaoNaoEncontradaException
import javax.persistence.Embeddable
import javax.validation.constraints.NotBlank

@Embeddable
class Instituicao(
    @field:NotBlank
    val nomeInstituicao: String,

    @field:NotBlank
    val ispb: String
) {

    companion object Factory {
        fun nomeByIspb(ispb: String) : String {
            val instituicao = listaInstituicoes().find { it.ispb == ispb }
                ?: throw throw InstituicaoNaoEncontradaException("Instituição não encontrada")

            return instituicao.nomeInstituicao
        }

        private fun listaInstituicoes():List<Instituicao> {
            return listOf(Instituicao(ispb = "00000000", nomeInstituicao = "Banco do Brasil S.A."),
                Instituicao(ispb = "00000208", nomeInstituicao = "BRB - BANCO DE BRASILIA S.A."),
                Instituicao(ispb = "00038121", nomeInstituicao = "Banco Central do Brasil - Selic"),
                Instituicao(ispb = "00038166", nomeInstituicao = "Banco Central do Brasil"),
                Instituicao(ispb = "00204963", nomeInstituicao = "COOPERATIVA DE CREDITO RURAL SEARA - CREDISEARA"),
                Instituicao(ispb = "00250699", nomeInstituicao = "AGK CORRETORA DE CAMBIO S.A."),
                Instituicao(ispb = "00315557", nomeInstituicao = "CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASIL"),
                Instituicao(ispb = "00329598", nomeInstituicao = "ÍNDIGO INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "00360305", nomeInstituicao = "CAIXA ECONOMICA FEDERAL"),
                Instituicao(ispb = "00394460", nomeInstituicao = "Secretaria do Tesouro Nacional - STN"),
                Instituicao(ispb = "00416968", nomeInstituicao = "Banco Inter S.A."),
                Instituicao(ispb = "00460065", nomeInstituicao = "COLUNA S/A DISTRIBUIDORA DE TITULOS E VALORES MOBILIÁRIOS"),
                Instituicao(ispb = "00517645", nomeInstituicao = "BANCO RIBEIRAO PRETO S.A."),
                Instituicao(ispb = "00556603", nomeInstituicao = "BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A."),
                Instituicao(ispb = "00558456", nomeInstituicao = "Banco Cetelem S.A."),
                Instituicao(ispb = "00795423", nomeInstituicao = "Banco Semear S.A."),
                Instituicao(ispb = "00806535", nomeInstituicao = "Planner Corretora de Valores S.A."),
                Instituicao(ispb = "00997185", nomeInstituicao = "Banco B3 S.A."),
                Instituicao(ispb = "01023570", nomeInstituicao = "Banco Rabobank International Brasil S.A."),
                Instituicao(ispb = "01027058", nomeInstituicao = "CIELO S.A."),
                Instituicao(ispb = "01073966", nomeInstituicao = "Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz"),
                Instituicao(ispb = "01181521", nomeInstituicao = "BANCO COOPERATIVO SICREDI S.A."),
                Instituicao(ispb = "01330387", nomeInstituicao = "COOPERATIVA DE CRÉDITO RURAL DE PEQUENOS AGRICULTORES E DA REFORMA AGRÁRIA DO CE"),
                Instituicao(ispb = "01522368", nomeInstituicao = "Banco BNP Paribas Brasil S.A."),
                Instituicao(ispb = "01658426", nomeInstituicao = "COOPERFORTE - COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DE FUNCIONÁRIOS DE INSTITUIÇÕES FINANCEIRAS PÚBLICAS FEDERAIS"),
                Instituicao(ispb = "01701201", nomeInstituicao = "Kirton Bank S.A. - Banco Múltiplo"),
                Instituicao(ispb = "01800019", nomeInstituicao = "PORTOCRED S.A. - CREDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "01852137", nomeInstituicao = "BBC LEASING S.A. - ARRENDAMENTO MERCANTIL"),
                Instituicao(ispb = "01858774", nomeInstituicao = "BANCO BV S.A."),
                Instituicao(ispb = "02038232", nomeInstituicao = "BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB"),
                Instituicao(ispb = "02276653", nomeInstituicao = "TRINUS CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "02318507", nomeInstituicao = "BANCO KEB HANA DO BRASIL S.A."),
                Instituicao(ispb = "02332886", nomeInstituicao = "XP INVESTIMENTOS CORRETORA DE CÂMBIO;TÍTULOS E VALORES MOBILIÁRIOS S/A"),
                Instituicao(ispb = "02398976", nomeInstituicao = "UNIPRIME NORTE DO PARANÁ - COOPERATIVA DE CRÉDITO LTDA"),
                Instituicao(ispb = "02685483", nomeInstituicao = "CM CAPITAL MARKETS CORRETORA DE CÂMBIO; TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "02801938", nomeInstituicao = "BANCO MORGAN STANLEY S.A."),
                Instituicao(ispb = "02819125", nomeInstituicao = "UBS Brasil Corretora de Câmbio; Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "02992317", nomeInstituicao = "Treviso Corretora de Câmbio S.A."),
                Instituicao(ispb = "02992335", nomeInstituicao = "Câmara Interbancária de Pagamentos - CIP - LDL"),
                Instituicao(ispb = "03012230", nomeInstituicao = "Hipercard Banco Múltiplo S.A."),
                Instituicao(ispb = "03017677", nomeInstituicao = "Banco J. Safra S.A."),
                Instituicao(ispb = "03046391", nomeInstituicao = "UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA."),
                Instituicao(ispb = "03215790", nomeInstituicao = "Banco Toyota do Brasil S.A."),
                Instituicao(ispb = "03311443", nomeInstituicao = "PARATI - CREDITO; FINANCIAMENTO E INVESTIMENTO S.A."),
                Instituicao(ispb = "03323840", nomeInstituicao = "Banco Alfa S.A."),
                Instituicao(ispb = "03502968", nomeInstituicao = "PI Distribuidora de Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "03532415", nomeInstituicao = "Banco ABN Amro S.A."),
                Instituicao(ispb = "03609817", nomeInstituicao = "Banco Cargill S.A."),
                Instituicao(ispb = "03751794", nomeInstituicao = "Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda."),
                Instituicao(ispb = "03881423", nomeInstituicao = "SOCINAL S.A. - CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "03973814", nomeInstituicao = "SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRANDE DO SUL"),
                Instituicao(ispb = "04062902", nomeInstituicao = "VISION S.A. CORRETORA DE CAMBIO"),
                Instituicao(ispb = "04184779", nomeInstituicao = "Banco Bradescard S.A."),
                Instituicao(ispb = "04257795", nomeInstituicao = "Nova Futura Corretora de Títulos e Valores Mobiliários Ltda."),
                Instituicao(ispb = "04307598", nomeInstituicao = "FIDÚCIA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LIMITADA"),
                Instituicao(ispb = "04332281", nomeInstituicao = "GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A."),
                Instituicao(ispb = "04391007", nomeInstituicao = "Câmara Interbancária de Pagamentos"),
                Instituicao(ispb = "04632856", nomeInstituicao = "Credisis - Central de Cooperativas de Crédito Ltda."),
                Instituicao(ispb = "04715685", nomeInstituicao = "COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RIO GRANDE DO SUL - SICOOB CREDITRAN"),
                Instituicao(ispb = "04814563", nomeInstituicao = "BANCO SOROCRED S.A. - BANCO MÚLTIPLO"),
                Instituicao(ispb = "04866275", nomeInstituicao = "Banco Inbursa S.A."),
                Instituicao(ispb = "04902979", nomeInstituicao = "BANCO DA AMAZONIA S.A."),
                Instituicao(ispb = "04913129", nomeInstituicao = "Confidence Corretora de Câmbio S.A."),
                Instituicao(ispb = "04913711", nomeInstituicao = "Banco do Estado do Pará S.A."),
                Instituicao(ispb = "05192316", nomeInstituicao = "Via Certa Financiadora S.A. - Crédito; Financiamento e Investimentos"),
                Instituicao(ispb = "05351887", nomeInstituicao = "ZEMA CRÉDITO; FINANCIAMENTO E INVESTIMENTO S/A"),
                Instituicao(ispb = "05442029", nomeInstituicao = "Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor"),
                Instituicao(ispb = "05463212", nomeInstituicao = "Cooperativa Central de Crédito - Ailos"),
                Instituicao(ispb = "05491616", nomeInstituicao = "COOPERATIVA DE CRÉDITO; POUPANÇA E SERVIÇOS FINANCEIROS DO CENTRO OESTE - CREDITO"),
                Instituicao(ispb = "05676026", nomeInstituicao = "Crediare S.A. - Crédito; financiamento e investimento"),
                Instituicao(ispb = "05684234", nomeInstituicao = "PLANNER SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR S.A."),
                Instituicao(ispb = "05790149", nomeInstituicao = "Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP"),
                Instituicao(ispb = "05841967", nomeInstituicao = "COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO DOS FABRICANTES DE CALÇADOS DE SAPIRANGA"),
                Instituicao(ispb = "06271464", nomeInstituicao = "Banco Bradesco BBI S.A."),
                Instituicao(ispb = "07207996", nomeInstituicao = "Banco Bradesco Financiamentos S.A."),
                Instituicao(ispb = "07237373", nomeInstituicao = "Banco do Nordeste do Brasil S.A."),
                Instituicao(ispb = "07253654", nomeInstituicao = "HEDGE INVESTMENTS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "07450604", nomeInstituicao = "China Construction Bank (Brasil) Banco Múltiplo S/A"),
                Instituicao(ispb = "07512441", nomeInstituicao = "HS FINANCEIRA S/A CREDITO; FINANCIAMENTO E INVESTIMENTOS"),
                Instituicao(ispb = "07652226", nomeInstituicao = "Lecca Crédito; Financiamento e Investimento S/A"),
                Instituicao(ispb = "07656500", nomeInstituicao = "Banco KDB do Brasil S.A."),
                Instituicao(ispb = "07679404", nomeInstituicao = "BANCO TOPÁZIO S.A."),
                Instituicao(ispb = "07693858", nomeInstituicao = "HSCM - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA"),
                Instituicao(ispb = "07799277", nomeInstituicao = "VALOR SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "07853842", nomeInstituicao = "COOPERATIVA DE CRÉDITO RURAL DE OURO   SULCREDI/OURO"),
                Instituicao(ispb = "07945233", nomeInstituicao = "PÓLOCRED   SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE"),
                Instituicao(ispb = "08240446", nomeInstituicao = "COOPERATIVA DE CREDITO RURAL DE IBIAM - SULCREDI/IBIAM"),
                Instituicao(ispb = "08253539", nomeInstituicao = "Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel"),
                Instituicao(ispb = "08357240", nomeInstituicao = "Banco CSF S.A."),
                Instituicao(ispb = "08561701", nomeInstituicao = "Pagseguro Internet S.A."),
                Instituicao(ispb = "08609934", nomeInstituicao = "MONEYCORP BANCO DE CÂMBIO S.A."),
                Instituicao(ispb = "08673569", nomeInstituicao = "F.D'GOLD - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "09089356", nomeInstituicao = "GERENCIANET S.A."),
                Instituicao(ispb = "09105360", nomeInstituicao = "ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda."),
                Instituicao(ispb = "09210106", nomeInstituicao = "SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE"),
                Instituicao(ispb = "09274232", nomeInstituicao = "STATE STREET BRASIL S.A. ? BANCO COMERCIAL"),
                Instituicao(ispb = "09313766", nomeInstituicao = "CARUANA S.A. - SOCIEDADE DE CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "09464032", nomeInstituicao = "MIDWAY S.A. - CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "09512542", nomeInstituicao = "Codepe Corretora de Valores e Câmbio S.A."),
                Instituicao(ispb = "09516419", nomeInstituicao = "Banco Original do Agronegócio S.A."),
                Instituicao(ispb = "09554480", nomeInstituicao = "Super Pagamentos e Administração de Meios Eletrônicos S.A."),
                Instituicao(ispb = "10264663", nomeInstituicao = "BancoSeguro S.A."),
                Instituicao(ispb = "10398952", nomeInstituicao = "CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E SOLIDÁRIA – CRESOL CONFEDERAÇÃO"),
                Instituicao(ispb = "10573521", nomeInstituicao = "MERCADOPAGO.COM REPRESENTACOES LTDA."),
                Instituicao(ispb = "10664513", nomeInstituicao = "Banco Agibank S.A."),
                Instituicao(ispb = "10690848", nomeInstituicao = "Banco da China Brasil S.A."),
                Instituicao(ispb = "10853017", nomeInstituicao = "Get Money Corretora de Câmbio S.A."),
                Instituicao(ispb = "10866788", nomeInstituicao = "Banco Bandepe S.A."),
                Instituicao(ispb = "11165756", nomeInstituicao = "GLOBAL FINANÇAS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE"),
                Instituicao(ispb = "11285104", nomeInstituicao = "Biorc Financeira - Crédito; Financiamento e Investimento S.A."),
                Instituicao(ispb = "11476673", nomeInstituicao = "BANCO RANDON S.A."),
                Instituicao(ispb = "11495073", nomeInstituicao = "OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "11581339", nomeInstituicao = "MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE"),
                Instituicao(ispb = "11703662", nomeInstituicao = "Travelex Banco de Câmbio S.A."),
                Instituicao(ispb = "11758741", nomeInstituicao = "Banco Finaxis S.A."),
                Instituicao(ispb = "11970623", nomeInstituicao = "BANCO SENFF S.A."),
                Instituicao(ispb = "12392983", nomeInstituicao = "MIRAE ASSET WEALTH MANAGEMENT (BRAZIL) CORRETORA DE CÂMBIO; TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "12865507", nomeInstituicao = "BRK S.A. Crédito; Financiamento e Investimento"),
                Instituicao(ispb = "13009717", nomeInstituicao = "Banco do Estado de Sergipe S.A."),
                Instituicao(ispb = "13059145", nomeInstituicao = "BEXS BANCO DE CÂMBIO S/A"),
                Instituicao(ispb = "13140088", nomeInstituicao = "Acesso Soluções de Pagamento S.A."),
                Instituicao(ispb = "13203354", nomeInstituicao = "FITBANK PAGAMENTOS ELETRONICOS S.A."),
                Instituicao(ispb = "13220493", nomeInstituicao = "BR Partners Banco de Investimento S.A."),
                Instituicao(ispb = "13293225", nomeInstituicao = "Órama Distribuidora de Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "13370835", nomeInstituicao = "BPP Instituição de Pagamento S.A."),
                Instituicao(ispb = "13486793", nomeInstituicao = "BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "13673855", nomeInstituicao = "Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "13720915", nomeInstituicao = "Banco Western Union do Brasil S.A."),
                Instituicao(ispb = "13884775", nomeInstituicao = "HUB PAGAMENTOS S.A"),
                Instituicao(ispb = "14190547", nomeInstituicao = "CAMBIONET CORRETORA DE CÂMBIO LTDA."),
                Instituicao(ispb = "14388334", nomeInstituicao = "PARANÁ BANCO S.A."),
                Instituicao(ispb = "14511781", nomeInstituicao = "BARI COMPANHIA HIPOTECÁRIA"),
                Instituicao(ispb = "15111975", nomeInstituicao = "IUGU INSTITUIÇÃO DE PAGAMENTO S.A."),
                Instituicao(ispb = "15114366", nomeInstituicao = "Banco Bocom BBM S.A."),
                Instituicao(ispb = "15173776", nomeInstituicao = "BANCO CAPITAL S.A."),
                Instituicao(ispb = "15357060", nomeInstituicao = "Banco Woori Bank do Brasil S.A."),
                Instituicao(ispb = "15581638", nomeInstituicao = "Facta Financeira S.A. - Crédito Financiamento e Investimento"),
                Instituicao(ispb = "16501555", nomeInstituicao = "Stone Pagamentos S.A."),
                Instituicao(ispb = "16927221", nomeInstituicao = "AMAZÔNIA CORRETORA DE CÂMBIO LTDA."),
                Instituicao(ispb = "16944141", nomeInstituicao = "Broker Brasil Corretora de Câmbio Ltda."),
                Instituicao(ispb = "17184037", nomeInstituicao = "Banco Mercantil do Brasil S.A."),
                Instituicao(ispb = "17298092", nomeInstituicao = "Banco Itaú BBA S.A."),
                Instituicao(ispb = "17351180", nomeInstituicao = "BANCO TRIANGULO S.A."),
                Instituicao(ispb = "17352220", nomeInstituicao = "SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A"),
                Instituicao(ispb = "17453575", nomeInstituicao = "ICBC do Brasil Banco Múltiplo S.A."),
                Instituicao(ispb = "17772370", nomeInstituicao = "Vip's Corretora de Câmbio Ltda."),
                Instituicao(ispb = "17826860", nomeInstituicao = "BMS SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "18188384", nomeInstituicao = "CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LTDA."),
                Instituicao(ispb = "18236120", nomeInstituicao = "NU PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO"),
                Instituicao(ispb = "18520834", nomeInstituicao = "UBS Brasil Banco de Investimento S.A."),
                Instituicao(ispb = "19307785", nomeInstituicao = "MS Bank S.A. Banco de Câmbio"),
                Instituicao(ispb = "19324634", nomeInstituicao = "LAMARA SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "20155248", nomeInstituicao = "PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "21018182", nomeInstituicao = "BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAMENTOS LTDA."),
                Instituicao(ispb = "21332862", nomeInstituicao = "CARTOS SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "22610500", nomeInstituicao = "VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA."),
                Instituicao(ispb = "22896431", nomeInstituicao = "PICPAY SERVICOS S.A."),
                Instituicao(ispb = "23522214", nomeInstituicao = "Commerzbank Brasil S.A. - Banco Múltiplo"),
                Instituicao(ispb = "23862762", nomeInstituicao = "WILL FINANCEIRA S.A. CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "24074692", nomeInstituicao = "GUITTA CORRETORA DE CAMBIO LTDA."),
                Instituicao(ispb = "24537861", nomeInstituicao = "FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA."),
                Instituicao(ispb = "26563270", nomeInstituicao = "COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE"),
                Instituicao(ispb = "27098060", nomeInstituicao = "Banco Digio S.A."),
                Instituicao(ispb = "27214112", nomeInstituicao = "AL5 S.A. CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "27302181", nomeInstituicao = "COOPERATIVA DE CREDITO DOS SERVIDORES DA UNIVERSIDADE FEDERAL DO ESPIRITO SANTO"),
                Instituicao(ispb = "27351731", nomeInstituicao = "REALIZE CRÉDITO; FINANCIAMENTO E INVESTIMENTO S.A."),
                Instituicao(ispb = "27652684", nomeInstituicao = "Genial Investimentos Corretora de Valores Mobiliários S.A."),
                Instituicao(ispb = "27842177", nomeInstituicao = "IB Corretora de Câmbio; Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "28127603", nomeInstituicao = "BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO"),
                Instituicao(ispb = "28195667", nomeInstituicao = "Banco ABC Brasil S.A."),
                Instituicao(ispb = "28650236", nomeInstituicao = "BS2 Distribuidora de Títulos e Valores Mobiliários S.A."),
                Instituicao(ispb = "28719664", nomeInstituicao = "Sistema do Balcão B3"),
                Instituicao(ispb = "29011780", nomeInstituicao = "Câmara Interbancária de Pagamentos - CIP C3"),
                Instituicao(ispb = "29030467", nomeInstituicao = "Scotiabank Brasil S.A. Banco Múltiplo"),
                Instituicao(ispb = "29162769", nomeInstituicao = "TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "30306294", nomeInstituicao = "Banco BTG Pactual S.A."),
                Instituicao(ispb = "30680829", nomeInstituicao = "NU FINANCEIRA S.A. - Sociedade de Crédito; Financiamento e Investimento"),
                Instituicao(ispb = "30723886", nomeInstituicao = "Banco Modal S.A."),
                Instituicao(ispb = "31597552", nomeInstituicao = "BANCO CLASSICO S.A."),
                Instituicao(ispb = "31749596", nomeInstituicao = "IDEAL CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "31872495", nomeInstituicao = "Banco C6 S.A."),
                Instituicao(ispb = "31880826", nomeInstituicao = "Banco Guanabara S.A."),
                Instituicao(ispb = "31895683", nomeInstituicao = "Banco Industrial do Brasil S.A."),
                Instituicao(ispb = "32062580", nomeInstituicao = "Banco Credit Suisse (Brasil) S.A."),
                Instituicao(ispb = "32402502", nomeInstituicao = "QI Sociedade de Crédito Direto S.A."),
                Instituicao(ispb = "32648370", nomeInstituicao = "FAIR CORRETORA DE CAMBIO S.A."),
                Instituicao(ispb = "32997490", nomeInstituicao = "Creditas Sociedade de Crédito Direto S.A."),
                Instituicao(ispb = "33042151", nomeInstituicao = "Banco de la Nacion Argentina"),
                Instituicao(ispb = "33042953", nomeInstituicao = "Citibank N.A."),
                Instituicao(ispb = "33132044", nomeInstituicao = "BANCO CEDULA S.A."),
                Instituicao(ispb = "33147315", nomeInstituicao = "Banco Bradesco BERJ S.A."),
                Instituicao(ispb = "33172537", nomeInstituicao = "BANCO J.P. MORGAN S.A."),
                Instituicao(ispb = "33264668", nomeInstituicao = "Banco XP S.A."),
                Instituicao(ispb = "33466988", nomeInstituicao = "Banco Caixa Geral - Brasil S.A."),
                Instituicao(ispb = "33479023", nomeInstituicao = "Banco Citibank S.A."),
                Instituicao(ispb = "33603457", nomeInstituicao = "BANCO RODOBENS S.A."),
                Instituicao(ispb = "33644196", nomeInstituicao = "Banco Fator S.A."),
                Instituicao(ispb = "33657248", nomeInstituicao = "BANCO NACIONAL DE DESENVOLVIMENTO ECONOMICO E SOCIAL"),
                Instituicao(ispb = "33775974", nomeInstituicao = "ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS; CÂMBIO E VALORES"),
                Instituicao(ispb = "33862244", nomeInstituicao = "BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "33885724", nomeInstituicao = "Banco Itaú Consignado S.A."),
                Instituicao(ispb = "33923798", nomeInstituicao = "BANCO MASTER S/A"),
                Instituicao(ispb = "34088029", nomeInstituicao = "LISTO SOCIEDADE DE CREDITO DIRETO S.A."),
                Instituicao(ispb = "34111187", nomeInstituicao = "Haitong Banco de Investimento do Brasil S.A."),
                Instituicao(ispb = "34335592", nomeInstituicao = "ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "34711571", nomeInstituicao = "VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "35551187", nomeInstituicao = "PLANTAE S.A. - CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "35977097", nomeInstituicao = "UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A."),
                Instituicao(ispb = "36113876", nomeInstituicao = "OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A."),
                Instituicao(ispb = "36586946", nomeInstituicao = "BONUSPAGO SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "36947229", nomeInstituicao = "COBUCCIO SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "37241230", nomeInstituicao = "SUMUP SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "37414009", nomeInstituicao = "ZIPDIN SOLUÇÕES DIGITAIS SOCIEDADE DE CRÉDITO DIRETO S/A"),
                Instituicao(ispb = "37526080", nomeInstituicao = "WORK SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "37715993", nomeInstituicao = "ACCREDITO - SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "37880206", nomeInstituicao = "CORA SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "38129006", nomeInstituicao = "NUMBRS SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "38224857", nomeInstituicao = "DELCRED SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "39343350", nomeInstituicao = "LAR COOPERATIVA DE CRÉDITO - LAR CREDI"),
                Instituicao(ispb = "39664698", nomeInstituicao = "CRED-SYSTEM SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "39669186", nomeInstituicao = "HEMERA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "39676772", nomeInstituicao = "CREDIFIT SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "40303299", nomeInstituicao = "PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA."),
                Instituicao(ispb = "40654622", nomeInstituicao = "TRINUS SOCIEDADE DE CRÉDITO DIRETO S.A."),
                Instituicao(ispb = "42272526", nomeInstituicao = "BNY Mellon Banco S.A."),
                Instituicao(ispb = "43180355", nomeInstituicao = "PEFISA S.A. - CRÉDITO; FINANCIAMENTO E INVESTIMENTO"),
                Instituicao(ispb = "44077014", nomeInstituicao = "BR-CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "44189447", nomeInstituicao = "Banco de La Provincia de Buenos Aires"),
                Instituicao(ispb = "45246410", nomeInstituicao = "BANCO GENIAL S.A."),
                Instituicao(ispb = "46518205", nomeInstituicao = "JPMorgan Chase Bank; National Association"),
                Instituicao(ispb = "48795256", nomeInstituicao = "Banco AndBank (Brasil) S.A."),
                Instituicao(ispb = "49336860", nomeInstituicao = "ING Bank N.V."),
                Instituicao(ispb = "50579044", nomeInstituicao = "LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA."),
                Instituicao(ispb = "50585090", nomeInstituicao = "BCV - BANCO DE CRÉDITO E VAREJO S.A."),
                Instituicao(ispb = "52904364", nomeInstituicao = "NECTON INVESTIMENTOS  S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES"),
                Instituicao(ispb = "52937216", nomeInstituicao = "Bexs Corretora de Câmbio S/A"),
                Instituicao(ispb = "53518684", nomeInstituicao = "BANCO HSBC S.A."),
                Instituicao(ispb = "54403563", nomeInstituicao = "Banco Arbi S.A."),
                Instituicao(ispb = "54641030", nomeInstituicao = "Câmara B3"),
                Instituicao(ispb = "55230916", nomeInstituicao = "Intesa Sanpaolo Brasil S.A. - Banco Múltiplo"),
                Instituicao(ispb = "57839805", nomeInstituicao = "Banco Tricury S.A."),
                Instituicao(ispb = "58160789", nomeInstituicao = "Banco Safra S.A."),
                Instituicao(ispb = "58497702", nomeInstituicao = "BANCO LETSBANK S.A."),
                Instituicao(ispb = "58616418", nomeInstituicao = "Banco Fibra S.A."),
                Instituicao(ispb = "59109165", nomeInstituicao = "Banco Volkswagen S.A."),
                Instituicao(ispb = "59118133", nomeInstituicao = "Banco Luso Brasileiro S.A."),
                Instituicao(ispb = "59274605", nomeInstituicao = "BANCO GM S.A."),
                Instituicao(ispb = "59285411", nomeInstituicao = "Banco Pan S.A."),
                Instituicao(ispb = "59588111", nomeInstituicao = "Banco Votorantim S.A."),
                Instituicao(ispb = "60394079", nomeInstituicao = "Banco ItauBank S.A."),
                Instituicao(ispb = "60498557", nomeInstituicao = "Banco MUFG Brasil S.A."),
                Instituicao(ispb = "60518222", nomeInstituicao = "Banco Sumitomo Mitsui Brasileiro S.A."),
                Instituicao(ispb = "60701190", nomeInstituicao = "ITAÚ UNIBANCO S.A."),
                Instituicao(ispb = "60746948", nomeInstituicao = "Banco Bradesco S.A."),
                Instituicao(ispb = "60814191", nomeInstituicao = "BANCO MERCEDES-BENZ DO BRASIL S.A."),
                Instituicao(ispb = "60850229", nomeInstituicao = "Omni Banco S.A."),
                Instituicao(ispb = "60872504", nomeInstituicao = "Itaú Unibanco Holding S.A."),
                Instituicao(ispb = "60889128", nomeInstituicao = "BANCO SOFISA S.A."),
                Instituicao(ispb = "60934221", nomeInstituicao = "Câmara de Câmbio B3"),
                Instituicao(ispb = "61024352", nomeInstituicao = "BANCO VOITER S.A."),
                Instituicao(ispb = "61033106", nomeInstituicao = "Banco Crefisa S.A."),
                Instituicao(ispb = "61088183", nomeInstituicao = "Banco Mizuho do Brasil S.A."),
                Instituicao(ispb = "61182408", nomeInstituicao = "Banco Investcred Unibanco S.A."),
                Instituicao(ispb = "61186680", nomeInstituicao = "Banco BMG S.A."),
                Instituicao(ispb = "61348538", nomeInstituicao = "BANCO C6 CONSIGNADO S.A."),
                Instituicao(ispb = "61444949", nomeInstituicao = "Sagitur Corretora de Câmbio Ltda."),
                Instituicao(ispb = "61533584", nomeInstituicao = "BANCO SOCIETE GENERALE BRASIL S.A."),
                Instituicao(ispb = "61723847", nomeInstituicao = "MAGLIANO S.A. CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS"),
                Instituicao(ispb = "61747085", nomeInstituicao = "TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA"),
                Instituicao(ispb = "61809182", nomeInstituicao = "CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A"),
                Instituicao(ispb = "61820817", nomeInstituicao = "Banco Paulista S.A."),
                Instituicao(ispb = "62073200", nomeInstituicao = "Bank of America Merrill Lynch Banco Múltiplo S.A."),
                Instituicao(ispb = "62109566", nomeInstituicao = "CREDISAN COOPERATIVA DE CRÉDITO"),
                Instituicao(ispb = "62144175", nomeInstituicao = "Banco Pine S.A."),
                Instituicao(ispb = "62169875", nomeInstituicao = "NU INVEST CORRETORA DE VALORES S.A."),
                Instituicao(ispb = "62232889", nomeInstituicao = "Banco Daycoval S.A."),
                Instituicao(ispb = "62237649", nomeInstituicao = "CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA."),
                Instituicao(ispb = "62285390", nomeInstituicao = "SINGULARE CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A."),
                Instituicao(ispb = "62287735", nomeInstituicao = "RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "62331228", nomeInstituicao = "DEUTSCHE BANK S.A. - BANCO ALEMAO"),
                Instituicao(ispb = "62421979", nomeInstituicao = "Banco Cifra S.A."),
                Instituicao(ispb = "65913436", nomeInstituicao = "Guide Investimentos S.A. Corretora de Valores"),
                Instituicao(ispb = "67030395", nomeInstituicao = "PLANNER TRUSTEE DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA."),
                Instituicao(ispb = "68757681", nomeInstituicao = "SIMPAUL CORRETORA DE CAMBIO E VALORES MOBILIARIOS  S.A."),
                Instituicao(ispb = "68900810", nomeInstituicao = "Banco Rendimento S.A."),
                Instituicao(ispb = "71027866", nomeInstituicao = "Banco BS2 S.A."),
                Instituicao(ispb = "71590442", nomeInstituicao = "Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda."),
                Instituicao(ispb = "71677850", nomeInstituicao = "Frente Corretora de Câmbio Ltda."),
                Instituicao(ispb = "73622748", nomeInstituicao = "B&T CORRETORA DE CAMBIO LTDA."),
                Instituicao(ispb = "74828799", nomeInstituicao = "Novo Banco Continental S.A. - Banco Múltiplo"),
                Instituicao(ispb = "75647891", nomeInstituicao = "BANCO CRÉDIT AGRICOLE BRASIL S.A."),
                Instituicao(ispb = "76461557", nomeInstituicao = "Cooperativa de Crédito Rural Coopavel"),
                Instituicao(ispb = "76543115", nomeInstituicao = "Banco Sistema S.A."),
                Instituicao(ispb = "76641497", nomeInstituicao = "DOURADA CORRETORA DE CÂMBIO LTDA."),
                Instituicao(ispb = "78157146", nomeInstituicao = "Credialiança Cooperativa de Crédito Rural"),
                Instituicao(ispb = "78626983", nomeInstituicao = "Banco VR S.A."),
                Instituicao(ispb = "78632767", nomeInstituicao = "Banco Ourinvest S.A."),
                Instituicao(ispb = "80271455", nomeInstituicao = "BANCO RNX S.A."),
                Instituicao(ispb = "81723108", nomeInstituicao = "CREDICOAMO CREDITO RURAL COOPERATIVA"),
                Instituicao(ispb = "82096447", nomeInstituicao = "COOPERATIVA DE ECONOMIA E CRÉDITO MÚTUO BRF - CREDIBRF"),
                Instituicao(ispb = "87963450", nomeInstituicao = "MAGNETIS - DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA"),
                Instituicao(ispb = "89960090", nomeInstituicao = "RB INVESTIMENTOS DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LIMITADA"),
                Instituicao(ispb = "90400888", nomeInstituicao = "BANCO SANTANDER (BRASIL) S.A."),
                Instituicao(ispb = "91884981", nomeInstituicao = "Banco John Deere S.A."),
                Instituicao(ispb = "92702067", nomeInstituicao = "Banco do Estado do Rio Grande do Sul S.A."),
                Instituicao(ispb = "92856905", nomeInstituicao = "ADVANCED CORRETORA DE CÂMBIO LTDA"),
                Instituicao(ispb = "92874270", nomeInstituicao = "BANCO DIGIMAIS S.A."),
                Instituicao(ispb = "92875780", nomeInstituicao = "WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMBIO LTDA."),
                Instituicao(ispb = "92894922", nomeInstituicao = "Banco Original S.A."),
                Instituicao(ispb = "94968518", nomeInstituicao = "DECYSEO CORRETORA DE CAMBIO LTDA."))
        }
    }
}